In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

In [3]:
np.NaN

nan

In [4]:
np.arange(0,1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a[2]

array([ 9, 10, 11, 12])

In [8]:
np.array([[0,0,0],
          [1,1,1]])

array([[0, 0, 0],
       [1, 1, 1]])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [14]:
np.arange(-2,-100,-5)

array([ -2,  -7, -12, -17, -22, -27, -32, -37, -42, -47, -52, -57, -62,
       -67, -72, -77, -82, -87, -92, -97])

In [15]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.append(arr,[1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [17]:
x = [1,2]
x.append([10,11])
x

[1, 2, [10, 11]]

In [18]:
np.delete(arr,1) # 1 di sini adalah indeks

array([1, 3, 4, 5, 6, 7, 8])

In [19]:
arr = np.array([[2,1,3,4,5,6,7,8],[3,4,5,1,2,6,7,8]])
arr

array([[2, 1, 3, 4, 5, 6, 7, 8],
       [3, 4, 5, 1, 2, 6, 7, 8]])

In [20]:
np.sort(arr)

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [21]:
arr.ndim

2

In [22]:
arr.size

16

In [23]:
arr.shape

(2, 8)

In [24]:
arr = np.array([[[0,1,2,3],
                 [4,5,6,7]],

                [[0,1,2,3],
                 [4,5,6,7]],

                [[0,1,2,3],
                 [4,5,6,7]]])
arr

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [25]:
arr.ndim

3

In [26]:
arr.size

24

In [27]:
arr.shape

(3, 2, 4)

In [28]:
arr = np.array([[1,2,3,4,5]])
arr

array([[1, 2, 3, 4, 5]])

In [29]:
arr.ndim

2

In [30]:
arr.size

5

In [31]:
arr.shape

(1, 5)

In [32]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [33]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [35]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [36]:
a2 = a[np.newaxis]
a2.shape

(1, 6)

In [37]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [38]:
row_vector = a[np.newaxis,:]
row_vector.shape

(1, 6)

In [39]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [40]:
col_vector = a[:,np.newaxis]
col_vector.shape

(6, 1)

In [41]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [42]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [43]:
b = np.expand_dims(a,axis=1)
b.shape

(6, 1)

In [44]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [45]:
c = np.expand_dims(a,axis=0)
c.shape

(1, 6)

In [46]:
c

array([[1, 2, 3, 4, 5, 6]])

# Indexing and Slicing

In [47]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [48]:
data[0]

1

In [49]:
data[1]

2

In [50]:
data[2]

3

In [51]:
data[0:2]

array([1, 2])

In [52]:
data[1:]

array([2, 3])

In [53]:
data[-2:]

array([2, 3])

In [54]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
# a[condition]

In [57]:
condition = (a >= 5)
a[condition]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [58]:
condition = (a % 2 == 0)
a[condition]

array([ 2,  4,  6,  8, 10, 12])

In [59]:
condition = (a > 2) & (a < 11)
a[condition]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Creating Array from Existing Data

In [61]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [63]:
a_1 = np.array([[1,1],[2,2]])
a_2 = np.array([[3,3],[4,4]])

In [64]:
a_1

array([[1, 1],
       [2, 2]])

In [65]:
a_2

array([[3, 3],
       [4, 4]])

In [66]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [67]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [68]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                     [13,14,15,16,17,18,19,20,21,22,23,24]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [70]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [71]:
a.shape

(3, 4)

In [72]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic Array Operations

In [74]:
# array_1 - array_2
# array_1 + array_2
# array_1 * array_2
# array_1 / array_2

In [75]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [76]:
a.sum()

10

In [77]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [78]:
b.sum(axis=0)

array([3, 3])

In [79]:
b.sum(axis=1)

array([2, 4])

In [80]:
data = np.array([1,2])
data

array([1, 2])

In [81]:
ones = np.ones(2)
ones

array([1., 1.])

In [82]:
data + ones

array([2., 3.])

In [83]:
data * ones

array([1., 2.])

In [84]:
data / ones

array([1., 2.])

In [85]:
data - ones

array([0., 1.])

# Broadcasting

In [86]:
data

array([1, 2])

In [87]:
data * 1.6

array([1.6, 3.2])

# More Array Operations

In [88]:
data.max()

2

In [89]:
data.min()

1

In [90]:
data.sum()

3

# Matrices

In [91]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [92]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [93]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [94]:
np.random.random((3,2))

array([[0.10801252, 0.99338893],
       [0.771178  , 0.19166276],
       [0.04960426, 0.86365346]])

In [95]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [96]:
ones = np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [97]:
data + ones

array([[2., 3.],
       [4., 5.]])

In [98]:
data * ones

array([[1., 2.],
       [3., 4.]])

In [99]:
data - ones

array([[0., 1.],
       [2., 3.]])

In [100]:
data / ones

array([[1., 2.],
       [3., 4.]])

# Dot Product

In [101]:
a_1 = np.array([[1,2,3],[4,5,6]])
a_1.shape

(2, 3)

In [102]:
a_2 = np.array(([7,8],[9,10],[11,12]))
a_2.shape

(3, 2)

In [103]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [104]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
data[0,1]

2

In [106]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [107]:
data[0:2,1]

array([2, 4])

# Matrix Aggregation

In [108]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
data.max()

6

In [110]:
data.min()

1

In [111]:
data.sum()

21

In [112]:
data.std()

1.707825127659933

In [113]:
data.max(axis=0)

array([5, 6])

In [114]:
data.max(axis=1)

array([2, 4, 6])

# Transposing and Reshaping

In [115]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [116]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [117]:
data_col = np.array([[1,2,3,4,5,6]])
data_col

array([[1, 2, 3, 4, 5, 6]])

In [118]:
data_col = data_col.T
data_col

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [119]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [120]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [121]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [122]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

# N-Dimensional Array

In [123]:
ndarr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [124]:
ndarr.shape

(2, 2, 2)

In [125]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [126]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [127]:
np.random.random((4,3,2))

array([[[0.39037196, 0.36411158],
        [0.31001731, 0.98471118],
        [0.14212124, 0.59471353]],

       [[0.33993404, 0.11623566],
        [0.3755148 , 0.99600214],
        [0.89377844, 0.39297894]],

       [[0.20096047, 0.76004632],
        [0.64344898, 0.62755966],
        [0.48788937, 0.93277125]],

       [[0.10787465, 0.57987156],
        [0.11153989, 0.60978384],
        [0.71029516, 0.43496574]]])

# Flatten N-Dimensional Array

In [128]:
arrflat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arrflat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [129]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [130]:
arrflat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [131]:
# error = (1/n) * np.sum(np.square(observed - prediction))